apiVersion: v1
kind: PersistentVolume
metadata:
  name: surrealdb-pv
spec:
  capacity:
    storage: 10Gi  # This should match the request in your PVC
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage  # This must match the PVC's storage class
  hostPath:
    path: /data/surrealdb  # Ensure this path exists on your node
