apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surrealdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage  # Reference the StorageClass
